version: '3.8'

services:
  sdf-pdbqt-converter:
    build:
      context: .
      target: production
    image: tr-grid/sdf-to-pdbqt:latest
    container_name: sdf-pdbqt-converter
    volumes:
      - ./data/input:/data/input:ro
      - ./data/output:/data/output
      - ./data/logs:/data/logs
    environment:
      - INPUT_BASE_DIR=/data/input
      - OUTPUT_BASE_DIR=/data/output
      - NUM_PROCESSES=4
      - MINIMIZATION_STRATEGY=balanced
      - TEST_MODE=true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 4G
          cpus: '2'

  sdf-pdbqt-converter-dev:
    build:
      context: .
      target: development
    image: tr-grid/sdf-to-pdbqt:dev
    container_name: sdf-pdbqt-converter-dev
    volumes:
      - .:/app
      - ./data/input:/data/input:ro
      - ./data/output:/data/output
      - ./data/logs:/data/logs
    environment:
      - INPUT_BASE_DIR=/data/input
      - OUTPUT_BASE_DIR=/data/output
      - NUM_PROCESSES=2
      - MINIMIZATION_STRATEGY=fast
      - TEST_MODE=true
    ports:
      - "8000:8000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'

  # Monitoring service (optional)
  monitoring:
    image: grafana/grafana:latest
    container_name: sdf-pdbqt-monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  grafana-storage: 