name: sdf_pdbqt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - rdkit>=2022.9.1
  - openbabel>=3.1.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pip
  - pip:
    - rdkit-pypi>=2022.9.1
    - colorlog>=6.7.0
    - multiprocessing-logging>=0.3.4 